package com.example.smarthiring.enums;

public enum CollaborateStatus {
    NOT_COLLABORATE,
    USER_REQUEST_COLLABORATE,
    PROJECT_REQUEST_COLLABORATE,
    COLLABORATING,
    USER_REJECT_COLLABORATE,
    PROJECT_REJECT_COLLABORATE;
}
